Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
theMachine = SLS_6502()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_2585/2046537104.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mtheMachine[0m [0;34m=[0m [0mSLS_6502[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_2585/377377113.py[0m in [0;36m__init__[0;34m(self)[0m
[1;32m     83[0m     [0;31m# constructor[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     84[0m     [0;32mdef[0m [0m__init__[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 85[0;31m         [0mself[0m[0;34m.[0m[0mcpu[0m        [0;34m=[0m [0mself[0m[0;34m.[0m[0mCPU[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     86[0m         [0mself[0m[0;34m.[0m[0mdatabus[0m    [0;34m=[0m [0mself[0m[0;34m.[0m[0mDataBus[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     87[0m         [0mself[0m[0;34m.[0m[0maddressbus[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mAddressBus[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/tmp/ipykernel_2585/377377113.py[0m in [0;36m__init__[0;34m(self)[0m
[1;32m     40[0m             [0mself[0m[0;34m.[0m[0m_Y[0m  [0;34m=[0m [0mself[0m[0;34m.[0m[0mRegister8Bit[0m[0;34m([0m[0;34m)[0m  [0;31m# Index Register Y[0m[0;34m[0m[0;34m[0m[0m
[1;32m     41[0m             [0mself[0m[0;34m.[0m[0m_PC[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mRegister16Bit[0m[0;34m([0m[0;34m)[0m [0;31m# Program Counter PC[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 42[0;31m             [0mself[0m[0;34m.[0m[0m_S[0m  [0;34m=[0m [0mself[0m[0;34m.[0m[0mRegister8bit[0m[0;34m([0m[0;34m)[0m  [0;31m# Stack Pointer S[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     43[0m             [0mself[0m[0;34m.[0m[0m_P[0m  [0;34m=[0m [0mself[0m[0;34m.[0m[0mRegisterProcessorStatus[0m[0;34m([0m[0;34m)[0m [0;31m# Processor Status Register P[0m[0;34m[0m[0;34m[0m[0m
[1;32m     44[0m [0;34m[0m[0m

[0;31mAttributeError[0m: 'CPU' object has no attribute 'Register8bit'
AttributeError: 'CPU' object has no attribute 'Register8bit'

