Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
display(Markdown(FileCodeBox(
    file="./myfunc0.s", 
    lang="gas", 
    title="<b>CODE: asm - myfunc0.s",
    h="100%", 
    w="107em"
)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/opt/app-root/src/UndertheCovers/underthecovers/python/common.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m display(Markdown(FileCodeBox(
[0m[1;32m      2[0m     [0mfile[0m[0;34m=[0m[0;34m"./myfunc0.s"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mlang[0m[0;34m=[0m[0;34m"gas"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mtitle[0m[0;34m=[0m[0;34m"<b>CODE: asm - myfunc0.s"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mh[0m[0;34m=[0m[0;34m"100%"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/app-root/src/UndertheCovers/underthecovers/python/common.py[0m in [0;36mFileCodeBox[0;34m(file, lang, number, **kwargs)[0m
[1;32m     63[0m [0;32mdef[0m [0mFileCodeBox[0m[0;34m([0m[0mfile[0m[0;34m,[0m [0mlang[0m[0;34m,[0m [0mnumber[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     64[0m     [0;31m#open text file in read mode[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 65[0;31m     [0mtext_file[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mfile[0m[0;34m,[0m [0;34m"r"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     66[0m     [0;31m#read whole file to a string[0m[0;34m[0m[0;34m[0m[0m
[1;32m     67[0m     [0mdata[0m [0;34m=[0m [0mtext_file[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './myfunc0.s'
FileNotFoundError: [Errno 2] No such file or directory: './myfunc0.s'

